// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChevronsController from "./chevrons_controller"
application.register("chevrons", ChevronsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)
